#ifndef _gc_card_h_
#define _gc_card_h_
#include "common.h"
extern unk __CARDBlock;
extern unk __CARDDiskNone;
extern unk __CARDVendorID;
extern void CARDInit(void /* TODO */);
extern void CARDProbeEx(void /* TODO */);
extern void CARDMount(void /* TODO */);
extern void CARDCheck(void /* TODO */);
extern void CARDUnmount(void /* TODO */);
extern void CARDFreeBlocks(void /* TODO */);
extern void CARDOpen(void /* TODO */);
extern void CARDGetStatus(void /* TODO */);
extern void CARDRead(void /* TODO */);
extern void CARDClose(void /* TODO */);
extern void CARDDelete(void /* TODO */);
extern void CARDCreate(void /* TODO */);
extern void CARDWrite(void /* TODO */);
extern void CARDSetStatus(void /* TODO */);
extern void CARDFormat(void /* TODO */);
extern void __CARDDefaultApiCallback(void /* TODO */);
extern void __CARDSyncCallback(void /* TODO */);
extern void __CARDExtHandler(void /* TODO */);
extern void __CARDExiHandler(void /* TODO */);
extern void __CARDReadStatus(void /* TODO */);
extern void __CARDClearStatus(void /* TODO */);
extern void __CARDTxHandler(void /* TODO */);
extern void __CARDUnlockedHandler(void /* TODO */);
extern void __CARDEnableInterrupt(void /* TODO */);
extern void __CARDReadSegment(void /* TODO */);
extern void __CARDWritePage(void /* TODO */);
extern void __CARDEraseSector(void /* TODO */);
extern void __CARDSetDiskID(void /* TODO */);
extern void __CARDGetControlBlock(void /* TODO */);
extern void __CARDPutControlBlock(void /* TODO */);
extern void __CARDSync(void /* TODO */);
extern void __CARDGetFatBlock(void /* TODO */);
extern void __CARDGetDirBlock(void /* TODO */);
extern void __CARDAllocBlock(void /* TODO */);
extern void __CARDUpdateFatBlock(void /* TODO */);
extern void __CARDFreeBlock(void /* TODO */);
extern void __CARDWrite(void /* TODO */);
extern void __CARDCheckSum(void /* TODO */);
extern void __CARDUpdateDir(void /* TODO */);
extern void __CARDVerify(void /* TODO */);
extern void CARDCheckExAsync(void /* TODO */);
extern void __CARDMountCallback(void /* TODO */);
extern void CARDMountAsync(void /* TODO */);
extern void __CARDUnlock(void /* TODO */);
extern void __CARDRead(void /* TODO */);
extern void __CARDFormatRegionAsync(void /* TODO */);
extern void __CARDCompareFileName(void /* TODO */);
extern void __CARDAccess(void /* TODO */);
extern void __CARDIsPublic(void /* TODO */);
extern void __CARDGetFileNo(void /* TODO */);
extern void __CARDIsOpened(void /* TODO */);
extern void CARDCreateAsync(void /* TODO */);
extern void __CARDSeek(void /* TODO */);
extern void CARDReadAsync(void /* TODO */);
extern void CARDWriteAsync(void /* TODO */);
extern void CARDDeleteAsync(void /* TODO */);
extern void CARDSetStatusAsync(void /* TODO */);
#endif
