#ifndef _gc_gx_h_
#define _gc_gx_h_
#include "common.h"
extern unk GXNtsc480IntDf;
extern unk GXPal528IntDf;
extern unk GXEurgb60Hz480IntDf;
extern unk GXMpal480IntDf;
extern unk GX_Black;
extern unk GX_White;
extern unk GX_Grey;
extern unk gx;
extern unk __GXCurrentBP;
extern unk GXNtsc240Ds;
extern unk GXNtsc240DsAa;
extern unk GXNtsc240Int;
extern unk GXNtsc240IntAa;
extern unk GXNtsc480Int;
extern unk GXNtsc480IntAa;
extern unk GXNtsc480Prog;
extern unk GXNtsc480ProgAa;
extern unk GXMpal240Ds;
extern unk GXMpal240DsAa;
extern unk GXMpal240Int;
extern unk GXMpal240IntAa;
extern unk GXMpal480Int;
extern unk GXMpal480IntAa;
extern unk GXPal264Ds;
extern unk GXPal264DsAa;
extern unk GXPal264Int;
extern unk GXPal264IntAa;
extern unk GXPal528Int;
extern unk GXPal524IntAa;
extern unk GXEurgb60Hz240Ds;
extern unk GXEurgb60Hz240DsAa;
extern unk GXEurgb60Hz240Int;
extern unk GXEurgb60Hz240IntAa;
extern unk GXEurgb60Hz480Int;
extern unk GXEurgb60Hz480IntAa;
extern unk GXRmHW;
extern unk GXTexMode0Ids;
extern unk GXTexMode1Ids;
extern unk GXTexImage0Ids;
extern unk GXTexImage1Ids;
extern unk GXTexImage2Ids;
extern unk GXTexImage3Ids;
extern unk GXTexTlutIds;
extern unk GX2HWFiltConv;
extern void GXDrawDone(void /* TODO */);
extern void GXSetChanMatColor(void /* TODO */);
extern void GXClearVtxDesc(void /* TODO */);
extern void GXSetVtxDesc(void /* TODO */);
extern void GXSetVtxAttrFmt(void /* TODO */);
extern void GXBegin(void /* TODO */);
extern void GXSetProjection(void /* TODO */);
extern void GXLoadPosMtxImm(void /* TODO */);
extern void GXSetCurrentMtx(void /* TODO */);
extern void GXSetZMode(void /* TODO */);
extern void GXSetNumChans(void /* TODO */);
extern void GXSetChanCtrl(void /* TODO */);
extern void GXSetNumTexGens(void /* TODO */);
extern void GXSetNumTevStages(void /* TODO */);
extern void GXSetTevOrder(void /* TODO */);
extern void GXSetTevOp(void /* TODO */);
extern void GXSetBlendMode(void /* TODO */);
extern void GXCopyDisp(void /* TODO */);
extern void GXFlush(void /* TODO */);
extern void GXInit(void /* TODO */);
extern void GXAdjustForOverscan(void /* TODO */);
extern void GXSetViewport(void /* TODO */);
extern void GXSetScissor(void /* TODO */);
extern void GXGetYScaleFactor(void /* TODO */);
extern void GXSetDispCopyYScale(void /* TODO */);
extern void GXSetDispCopySrc(void /* TODO */);
extern void GXSetDispCopyDst(void /* TODO */);
extern void GXSetCopyFilter(void /* TODO */);
extern void GXSetPixelFmt(void /* TODO */);
extern void GXSetDispCopyGamma(void /* TODO */);
extern void GXSetDrawSync(void /* TODO */);
extern void GXClearGPMetric(void /* TODO */);
extern void GXSetViewportJitter(void /* TODO */);
extern void GXSetTevColorIn(void /* TODO */);
extern void GXSetTevSwapMode(void /* TODO */);
extern void GXSetTevAlphaIn(void /* TODO */);
extern void GXSetTevColorOp(void /* TODO */);
extern void GXSetTevAlphaOp(void /* TODO */);
extern void GXGetGPStatus(void /* TODO */);
extern void GXReadDrawSync(void /* TODO */);
extern void GXSetGPMetric(void /* TODO */);
extern void GXReadXfRasMetric(void /* TODO */);
extern void GXGetCPUFifo(void /* TODO */);
extern void GXGetFifoBase(void /* TODO */);
extern void GXGetFifoSize(void /* TODO */);
extern void GXAbortFrame(void /* TODO */);
extern void GXInitFifoBase(void /* TODO */);
extern void GXSetCPUFifo(void /* TODO */);
extern void GXSetGPFifo(void /* TODO */);
extern void GXInitTexObj(void /* TODO */);
extern void GXInitTexObjLOD(void /* TODO */);
extern void GXLoadTexObj(void /* TODO */);
extern void GXLoadTexMtxImm(void /* TODO */);
extern void GXSetTexCoordGen2(void /* TODO */);
extern void GXSetAlphaCompare(void /* TODO */);
extern void GXSetTevSwapModeTable(void /* TODO */);
extern void GXSetClipMode(void /* TODO */);
extern void GXSetZCompLoc(void /* TODO */);
extern void GXSetAlphaUpdate(void /* TODO */);
extern void GXSetCullMode(void /* TODO */);
extern void GXInvalidateTexAll(void /* TODO */);
extern void GXSetCopyClear(void /* TODO */);
extern void GXGetTexBufferSize(void /* TODO */);
extern void GXSetFog(void /* TODO */);
extern void GXLoadNrmMtxImm(void /* TODO */);
extern void GXSetTexCopySrc(void /* TODO */);
extern void GXSetTexCopyDst(void /* TODO */);
extern void GXCopyTex(void /* TODO */);
extern void GXPixModeSync(void /* TODO */);
extern void GXSetChanAmbColor(void /* TODO */);
extern void GXInitLightPos(void /* TODO */);
extern void GXInitLightColor(void /* TODO */);
extern void GXLoadLightObjImm(void /* TODO */);
extern void GXSetArray(void /* TODO */);
extern void GXSetPointSize(void /* TODO */);
extern void GXInitTexObjWrapMode(void /* TODO */);
extern void __GXInitGX(void /* TODO */);
extern void GXGetTexObjFmt(void /* TODO */);
extern void __GXFifoInit(void /* TODO */);
extern void __GXPEInit(void /* TODO */);
extern void __GXFlushTextureState(void /* TODO */);
extern void GXInitTexCacheRegion(void /* TODO */);
extern void GXInitTlutRegion(void /* TODO */);
extern void __GXSetTmemConfig(void /* TODO */);
extern void GXInvalidateVtxCache(void /* TODO */);
extern void GXSetLineWidth(void /* TODO */);
extern void GXEnableTexOffsets(void /* TODO */);
extern void GXSetCoPlanar(void /* TODO */);
extern void GXSetScissorBoxOffset(void /* TODO */);
extern void GXSetTexRegionCallback(void /* TODO */);
extern void GXSetTlutRegionCallback(void /* TODO */);
extern void GXSetZTexture(void /* TODO */);
extern void GXSetTevKColorSel(void /* TODO */);
extern void GXSetTevKAlphaSel(void /* TODO */);
extern void GXSetTevDirect(void /* TODO */);
extern void GXSetNumIndStages(void /* TODO */);
extern void GXSetIndTexCoordScale(void /* TODO */);
extern void GXSetFogRangeAdj(void /* TODO */);
extern void GXSetColorUpdate(void /* TODO */);
extern void GXSetDither(void /* TODO */);
extern void GXSetDstAlpha(void /* TODO */);
extern void GXSetFieldMask(void /* TODO */);
extern void GXSetFieldMode(void /* TODO */);
extern void GXSetCopyClamp(void /* TODO */);
extern void GXSetDispCopyFrame2Field(void /* TODO */);
extern void GXClearBoundingBox(void /* TODO */);
extern void GXPokeColorUpdate(void /* TODO */);
extern void GXPokeAlphaUpdate(void /* TODO */);
extern void GXPokeDither(void /* TODO */);
extern void GXPokeBlendMode(void /* TODO */);
extern void GXPokeAlphaMode(void /* TODO */);
extern void GXPokeAlphaRead(void /* TODO */);
extern void GXPokeDstAlpha(void /* TODO */);
extern void GXPokeZMode(void /* TODO */);
extern void GXInitFifoLimits(void /* TODO */);
extern void GXInitFifoPtrs(void /* TODO */);
extern void __GXCleanGPFifo(void /* TODO */);
extern void GXGetGPFifo(void /* TODO */);
extern void GXSetVtxDescv(void /* TODO */);
extern void __GXSetVCD(void /* TODO */);
extern void GXGetVtxDesc(void /* TODO */);
extern void GXSetVtxAttrFmtv(void /* TODO */);
extern void __GXSetVAT(void /* TODO */);
extern void GXGetVtxAttrFmt(void /* TODO */);
extern void __GXSetMatrixIndex(void /* TODO */);
extern void __GXSetDirtyState(void /* TODO */);
extern void __GXSetGenMode(void /* TODO */);
extern void __GXSendFlushPrim(void /* TODO */);
extern void __GXSetSUTexRegs(void /* TODO */);
extern void __GXUpdateBPMask(void /* TODO */);
extern void GXInitLightSpot(void /* TODO */);
extern void GXLoadTexObjPreLoaded(void /* TODO */);
extern void GXSetTevIndirect(void /* TODO */);
extern void __GXSetRange(void /* TODO */);
extern void GXReadGPMetric(void /* TODO */);
#endif
